[[constraints]]
== Documenting constraints

Spring REST Docs has support for documenting constraints,
but using them requires a bit of work and you have to decide on how to include them.
Here we are going a step further and automatically use constraints
and the constraint groups to derive whether a field is optional
and to add the constraint descriptions to the field descriptions.

.Example
[source,java]
----
/**
 * Username
 */
@NotNull
@Size(min = 2, max = 50)
private String username;
----

.Result
|===
|Parameter|Type|Optional|Description

| username
| String
| false
| Username.

Size must be between 2 and 50.

|===

[[constraints-optionality]]
=== Constraints that determine optionality

The following three constraints are used to determine whether a field is optional.
Their descriptions are not included in the field descriptions.

* NotNull
* NotEmpty
* NotBlank

Along with JSR-303 annotations, optionality is also determined based on:

* `required` parameter of `@RequestParam`
* field type being `java.util.Optional`
* Koltin field being non-nullable

[[constraints-custom]]
=== Custom constraints

Descriptions for custom constraints can be provided in `org.springframework.restdocs.constraints.ConstraintDescriptions.properties`.
If this file can be loaded as a resource, descriptions are extracted.
Each description is a property where the key is the full class name of the annotation suffixed with `.description`.
The value is the description and can contain placeholders for annotation methods,
e.g. `${value}` to get the content of `value()`.
For more details, see original documentation of http://docs.spring.io/spring-restdocs/docs/${spring-restdocs.version}/reference/html5/#documenting-your-api-constraints-describing[here].

Example for the constraint annotation `myproject.constraints.OneOf`:

.ConstraintDescriptions.properties
[source,ini]
----
myproject.constraints.OneOf.description=Must be one of ${value}
----

[[constraints-enums]]
=== Enums

Constraint message for enum is appended to description field as list of allowed values, e.g. `Must be one of [A, B]`.
If you want to customize this message, use <<constraints-custom,above mentioned>> `ConstraintDescriptions.properties` approach.
The list of values is represented by the `${value}` placeholder.

[[constraints-readable-values]]
=== Readable constraint values

Spring REST Docs just calls `toString()` objects extracted from
the constraint for documentation.
Here we do a bit more on the following two types:

* Array: The elements are extracted and `toString()` is called
on each element. The resulting strings are wrapped in brackets
and separated by commas, i.e. `[element1.toString(), element2.toString(), ...]`.
* Class: An instance with the default constructor is created
and `toString()` is called on the instance.

[[constraints-groups]]
=== Constraint groups

Constraint groups are also included in the documentation if
a description is provided for them.
The descriptions are provided in the same way as for custom constraints.

[[constraints-examples]]
==== Examples

[[constraints-examples-descriptions]]
===== Descriptions for the examples

.ConstraintDescriptions.properties
[source,ini]
----
myproject.constraints.groups.German.description=DE: ${value}
myproject.constraints.groups.English.description=EN: ${value}
myproject.constraints.OneOf.description=Must be one of ${value}
----

[[constraints-examples-optionality]]
===== Optionality description

.Code
[source,java]
----
@NotNull(groups = English.class)
private String field;
----

.Result
|===
|Parameter|Type|Optional|Description

| field
| String
| true +
EN: false
|

|===

[[constraints-examples-fields]]
===== Field description example

.Code
[source,java]
----
@OneOf(value = {"big", "small"}, groups = English.class)
private String field;
----

.Result
|===
|Parameter|Type|Optional|Description

| field
| String
| true
| EN: Must be one of [big, small]

|===

