[[contributing]]
== Contributing

[[contributing-building]]
=== Building from source

[[contributing-installing-testjar]]
==== Install Spring REST Docs test JAR

The Spring REST Docs test JAR is not published via Maven, but this project relies on it.
If you want to build this project yourself, you need to install the test JAR.
The test JAR is located in the lib folder and can be installed as follow:

.Bash
[source,bash]
----
mvn install:install-file -Dfile=lib/spring-restdocs-core-${spring-restdocs.version}-test.jar \
    -DgroupId=org.springframework.restdocs -DartifactId=spring-restdocs-core \
    -Dversion=${spring-restdocs.version} -Dpackaging=test-jar -Dclassifier=test
----

[[contributing-building-testjar]]
==== Build Spring REST Docs test JAR

Building the Spring REST Docs test JAR is not required to build the project,
but if you ever want to upgrade the version of Spring REST Docs in this project this step has to be done.

We use version ${spring-restdocs.version} of Spring REST Docs in this example.

You find the currently required version in `pom.xml`:

.Maven
[source,xml]
----
<dependency>
    <groupId>org.springframework.restdocs</groupId>
    <artifactId>spring-restdocs-core</artifactId>
    <version>${spring-restdocs.version}</version>
    <classifier>test</classifier>
    <scope>test</scope>
</dependency>
----

Clone and build a specific version of Spring REST Docs:

.Bash
[source,bash]
----
git clone git@github.com:spring-projects/spring-restdocs.git
cd spring-restdocs
git fetch --tags
git checkout tags/v${spring-restdocs.version}
./gradlew build
----

Afterwards the test JAR is located at
`spring-restdocs/spring-restdocs-core/build/libs/spring-restdocs-core-${spring-restdocs.version}-test.jar`
and has to be installed with the Maven command shown in the section above.

[[contributing-building-build]]
==== Build

.Bash (in root folder)
[source,bash]
----
mvn install
----
