[[contributing]]
== Contributing

[[contributing-building]]
=== Building from source

[[contributing-building-testjar]]
==== Get spring-restdocs-core test JAR

The Spring REST Docs test JAR is not published via Maven, but this project relies on it.
If you want to build this project yourself, you need the test JAR in the Maven cache of your system.
You can either copy the JAR from the lib folder of this project or you can build it yourself and copy afterwards.

We use version ${spring-restdocs.version} of Spring REST Docs in this example.

You find the currently required version in `pom.xml`:

.Maven
[source,xml]
----
<dependency>
    <groupId>org.springframework.restdocs</groupId>
    <artifactId>spring-restdocs-core</artifactId>
    <version>${spring-restdocs.version}</version>
    <classifier>test</classifier>
    <scope>test</scope>
</dependency>
----

Clone and build a specific version of Spring REST Docs:

.Bash
[source,bash]
----
git clone git@github.com:spring-projects/spring-restdocs.git
cd spring-restdocs
git fetch --tags
git checkout tags/v${spring-restdocs.version}
./gradlew build
----

Afterwards you copy
`spring-restdocs/spring-restdocs-core/build/libs/spring-restdocs-core-${spring-restdocs.version}-test.jar`
to
`~/.m2/repository/org/springframework/restdocs/spring-restdocs-core/${spring-restdocs.version}`
so that the test JAR is available to Maven.

[[contributing-building-build]]
==== Build

.Bash (in root folder)
[source,bash]
----
mvn install
----

