[[gettingstarted]]
== Getting started

[[gettingstarted-requirements]]
=== Requirements

Spring Auto REST Docs has the following minimum requirements:

* Java 7
* Spring REST Docs ${spring-restdocs.version} (see http://docs.spring.io/spring-restdocs/docs/${spring-restdocs.version}/reference/html5/[documentation])
* Jackson has to be used for creating and parsing JSON

[[gettingstarted-usage]]
=== Usage

. Setup project for http://docs.spring.io/spring-restdocs/docs/${spring-restdocs.version}/reference/html5/#getting-started[Spring REST Docs]

. Additional configuration for this extension:
+
[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
.Maven
----
<dependency>
    <groupId>capital.scalable</groupId>
    <artifactId>spring-auto-restdocs-core</artifactId>
    <version>1.0.5</version>
    <scope>test</scope> <1>
</dependency>

<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
             <configuration>
                <includes>
                    <include>**/*Test.java</include>
                </includes>
                <systemPropertyVariables>
                    <org.springframework.restdocs.outputDir>
                        \${snippetsDirectory}
                    </org.springframework.restdocs.outputDir>
                    <org.springframework.restdocs.javadocJsonDir>
                        \${project.build.directory}/generated-javadoc-json <2>
                    </org.springframework.restdocs.javadocJsonDir>
                </systemPropertyVariables>
             </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-javadoc-plugin</artifactId>
            <extensions>true</extensions>
            <executions>
                <execution>
                    <phase>compile</phase>
                    <goals>
                        <goal>javadoc-no-fork</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <doclet>capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet</doclet>
                <docletArtifact>
                    <groupId>capital.scalable</groupId>
                    <artifactId>spring-auto-restdocs-json-doclet</artifactId>
                    <version>1.0.5</version>
                </docletArtifact>
                <destDir>generated-javadoc-json</destDir>
                <reportOutputDirectory>\${project.build.directory}</reportOutputDirectory>
                <useStandardDocletOptions>false</useStandardDocletOptions>
                <show>package</show>
            </configuration>
        </plugin>
        ...
    </plugins>
</build>
----
<1> Has to be removed if `@RestdocsNotExpanded` is used.
<2> Multiple directories can be listed by separating them with `;`.
The directories are processed in order and only the first found JSON file is used.
+
[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle
----
configurations {
    jsondoclet
}

ext {
    javadocJsonDir = file("$buildDir/generated-javadoc-json") <1>
}

dependencies {
    testCompile group: 'capital.scalable', name: 'spring-auto-restdocs-core', version: '1.0.5' <2>
    jsondoclet group: 'capital.scalable', name: 'spring-auto-restdocs-json-doclet', version: '1.0.5'
}

task jsonDoclet(type: Javadoc, dependsOn: compileJava) {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath
    destinationDir = javadocJsonDir
    options.docletpath = configurations.jsondoclet.files.asType(List)
    options.doclet = 'capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet'
    options.memberLevel = JavadocMemberLevel.PACKAGE
}

test {
    systemProperty 'org.springframework.restdocs.outputDir', snippetsDir
    systemProperty 'org.springframework.restdocs.javadocJsonDir', javadocJsonDir

    dependsOn jsonDoclet
}

jar {
    dependsOn asciidoctor
}
----
<1> Multiple directories can be listed by separating them with `;`.
The directories are processed in order and only the first found JSON file is used.
<2> Has to be `compile` instead of `testCompile` if `@RestdocsNotExpanded` is used.

. Configure MockMvc
+
[source,java,indent=0,role="secondary"]
----
@Autowired
private WebApplicationContext context;

@Autowired
protected ObjectMapper objectMapper;

protected MockMvc mockMvc;

@Rule
public final JUnitRestDocumentation restDocumentation = new JUnitRestDocumentation(
    System.getProperties().getProperty("org.springframework.restdocs.outputDir"));

@Before
public void setUp() throws Exception {
    this.mockMvc = MockMvcBuilders
            .webAppContextSetup(context)
            .addFilters(springSecurityFilterChain)
            .alwaysDo(JacksonResultHandlers.prepareJackson(objectMapper))
            .alwaysDo(MockMvcRestDocumentation.document("{class-name}/{method-name}",
                    Preprocessors.preprocessRequest(),
                    Preprocessors.preprocessResponse(
                            ResponseModifyingPreprocessors.replaceBinaryContent(),
                            ResponseModifyingPreprocessors.limitJsonArrayLength(objectMapper),
                            Preprocessors.prettyPrint())))
            .apply(MockMvcRestDocumentation.documentationConfiguration(restDocumentation)
                    .uris()
                    .withScheme("http")
                    .withHost("localhost")
                    .withPort(8080)
                    .and().snippets()
                    .withDefaults(CliDocumentation.curlRequest(),
                            HttpDocumentation.httpRequest(),
                            HttpDocumentation.httpResponse(),
                            AutoDocumentation.requestFields(),
                            AutoDocumentation.responseFields(),
                            AutoDocumentation.pathParameters(),
                            AutoDocumentation.requestParameters(),
                            AutoDocumentation.description(),
                            AutoDocumentation.methodAndPath(),
                            AutoDocumentation.section()))
            .build();
}
----

[[gettingstarted-sample]]
=== Sample application

https://github.com/ScaCap/spring-auto-restdocs/tree/master/spring-auto-restdocs-example[This project] includes a sample application that demonstrates most features:

The generated documentation of the example project can be viewed https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/generated-docs/index.html[here].
