[[gettingstarted]]
== Getting started

[[gettingstarted-requirements]]
=== Requirements

Spring Auto REST Docs has the following minimum requirements:

* Java 8 or Kotlin 1.3
* Spring REST Docs ${spring-restdocs.version} (see http://docs.spring.io/spring-restdocs/docs/${spring-restdocs.version}/reference/html5/[documentation])
* Jackson has to be used for creating and parsing JSON

For Java 7 and Spring REST Docs 1.2.x support,
please use the 1.0.x version of Spring Auto REST Docs.

For Java 9+ support, use `spring-auto-restdocs-json-doclet-jdk9` as doclet dependency.
Our support is focused on the latest Kotlin version, Java 8 and 11.
In addition, we try to support the latest Java version that is supported by Spring.

[[gettingstarted-usage]]
=== Usage

. Setup project for http://docs.spring.io/spring-restdocs/docs/${spring-restdocs.version}/reference/html5/#getting-started[Spring REST Docs]

. Additional configuration for this extension:
+
[source,xml]
.Maven
----
<dependency>
    <groupId>capital.scalable</groupId>
    <artifactId>spring-auto-restdocs-core</artifactId>
    <version>${latestRelease}</version>
    <scope>test</scope>
</dependency>

<build>
    <plugins>
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
             <configuration>
                <includes>
                    <include>**/*Test.java</include>
                </includes>
                <systemPropertyVariables>
                    <org.springframework.restdocs.outputDir>
                        \${project.build.directory}/generated-snippets <1>
                    </org.springframework.restdocs.outputDir>
                    <org.springframework.restdocs.javadocJsonDir>
                        \${project.build.directory}/generated-javadoc-json <2>
                    </org.springframework.restdocs.javadocJsonDir>
                </systemPropertyVariables>
             </configuration>
        </plugin>
        <plugin>
            <artifactId>maven-javadoc-plugin</artifactId>
            <extensions>true</extensions>
            <executions>
                <execution>
                    <id>generate-javadoc-json</id>
                    <phase>compile</phase>
                    <goals>
                        <goal>javadoc-no-fork</goal>
                    </goals>
                    <configuration>
                        <doclet>capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet</doclet>
                        <docletArtifact>
                            <groupId>capital.scalable</groupId>
                            <artifactId>spring-auto-restdocs-json-doclet</artifactId> <3>
                            <version>${latestRelease}</version>
                        </docletArtifact>
                        <destDir>generated-javadoc-json</destDir> <2>
                        <reportOutputDirectory>\${project.build.directory}</reportOutputDirectory> <2>
                        <useStandardDocletOptions>false</useStandardDocletOptions>
                        <show>package</show>
                    </configuration>
                </execution>
            </executions>
        </plugin>
        ...
    </plugins>
</build>
----
<1> (Optional) Determines directory where snippets are saved. Defaults to `generated-snippets` in build directory.
<2> (Optional) Determines where JSON files are saved. Defaults to `generated-javadoc-json` in build directory.
Multiple directories can be listed by separating them with `,`.
The directories are processed in order and only the first found JSON file is used.
<3> For Java 9/10/11 support, use `spring-auto-restdocs-json-doclet-jdk9` as doclet dependency.

+
[source,javascript]
.Gradle
----
configurations {
    jsondoclet
}

ext {
    javadocJsonDir = file("$buildDir/generated-javadoc-json") <2>
}

dependencies {
    testCompile group: 'capital.scalable', name: 'spring-auto-restdocs-core', version: '${latestRelease}'
    jsondoclet group: 'capital.scalable', name: 'spring-auto-restdocs-json-doclet', version: '${latestRelease}' <3>
}

task jsonDoclet(type: Javadoc, dependsOn: compileJava) {
    source = sourceSets.main.allJava
    classpath = sourceSets.main.compileClasspath
    destinationDir = javadocJsonDir <2>
    options.docletpath = configurations.jsondoclet.files.asType(List)
    options.doclet = 'capital.scalable.restdocs.jsondoclet.ExtractDocumentationAsJsonDoclet'
    options.memberLevel = JavadocMemberLevel.PACKAGE
}

test {
    systemProperty 'org.springframework.restdocs.outputDir', snippetsDir <1>
    systemProperty 'org.springframework.restdocs.javadocJsonDir', javadocJsonDir <2>

    dependsOn jsonDoclet
}

jar {
    dependsOn asciidoctor
}
----
<1> (Optional) Determines directory where snippets are saved. Defaults to `generated-snippets` in build directory.
<2> (Optional) Determines where JSON files are saved.
Defaults to `generated-javadoc-json` in build directory.
Multiple directories can be listed by separating them with `,`.
The directories are processed in order and only the first found JSON file is used.
<3> For Java 9/10/11 support, use `spring-auto-restdocs-json-doclet-jdk9` as doclet dependency.

. Configure MockMvc or WebTestClient
+
[source,java]
.MockMvc Test class
----
@Autowired
private WebApplicationContext context;

@Autowired
protected ObjectMapper objectMapper;

protected MockMvc mockMvc;

@Rule
public final JUnitRestDocumentation restDocumentation = new JUnitRestDocumentation();

@Before
public void setUp() throws Exception {
    this.mockMvc = MockMvcBuilders
            .webAppContextSetup(context)
            .addFilters(springSecurityFilterChain)
            .alwaysDo(JacksonResultHandlers.prepareJackson(objectMapper))
            .alwaysDo(MockMvcRestDocumentation.document("{class-name}/{method-name}",
                    Preprocessors.preprocessRequest(),
                    Preprocessors.preprocessResponse(
                            ResponseModifyingPreprocessors.replaceBinaryContent(),
                            ResponseModifyingPreprocessors.limitJsonArrayLength(objectMapper),
                            Preprocessors.prettyPrint())))
            .apply(MockMvcRestDocumentation.documentationConfiguration(restDocumentation)
                    .uris()
                    .withScheme("http")
                    .withHost("localhost")
                    .withPort(8080)
                    .and().snippets()
                    .withDefaults(CliDocumentation.curlRequest(),
                            HttpDocumentation.httpRequest(),
                            HttpDocumentation.httpResponse(),
                            AutoDocumentation.requestFields(),
                            AutoDocumentation.responseFields(),
                            AutoDocumentation.pathParameters(),
                            AutoDocumentation.requestParameters(),
                            AutoDocumentation.description(),
                            AutoDocumentation.methodAndPath(),
                            AutoDocumentation.section()))
            .build();
}
----
+
[source,java]
.WebTestClient Test class
----
@Autowired
private ApplicationContext context;

protected WebTestClient webTestClient;

@Rule
public final JUnitRestDocumentation restDocumentation = new JUnitRestDocumentation();

@Before
public void setUp() throws Exception {
    this.webTestClient = WebTestClient
            .bindToApplicationContext(context)
            .apply(springSecurity())
            .configureClient()
            .baseUrl("http://localhost:8080/")
            .filter(documentationConfiguration(restDocumentation)
                .snippets()
                .withDefaults(WebTestClientInitializer.prepareSnippets(context),
                           CliDocumentation.curlRequest(),
                           HttpDocumentation.httpRequest(),
                           HttpDocumentation.httpResponse(),
                           AutoDocumentation.requestFields(),
                           AutoDocumentation.responseFields(),
                           AutoDocumentation.pathParameters(),
                           AutoDocumentation.requestParameters(),
                           AutoDocumentation.description(),
                           AutoDocumentation.methodAndPath(),
                           AutoDocumentation.section()))
            .build();
}
----

[[gettingstarted-snapshot]]
=== Snapshot build

If you want to experiment with snapshot builds, add this repository:

[source,xml]
.Maven
----
<repositories>
    <repository>
        <id>sonatype-snapshots</id>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
----

[source,javascript]
.Gradle
----
repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
----

[[gettingstarted-sample]]
=== Sample applications

This projects includes a
https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/java-webmvc[Java Web MVC example],
a
https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/java-webflux[Java WebFlux example]
and a
https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/kotlin-webmvc[Kotlin Web MVC example]
application that demonstrate most features.

The generated documentation can be viewed for the
https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/java-webmvc/generated-docs/index.html[Java Web MVC example],
the
https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/java-webflux/generated-docs/index.html[Java WebFlux example]
and the
https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/samples/kotlin-webmvc/generated-docs/index.html[Kotlin Web MCV example].
