= Spring Auto REST Docs
Scalable Capital
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjsdir: highlight
:toc: left
:toclevels: 2
:sectlinks:
:table-caption!:
:revnumber: ${project.version}

[[abstract]]

The aim of this extension to Spring REST Docs is to help you to write
even less -- both code and documentation.
You still get the same nice documentation as with Spring REST Docs itself.
The main benefit is that writing less and moving the documentation closer
to the code increases the maintainability of the documentation.

In Spring REST Docs you have to add the documentation for your JSON with
a DSL in your test. We moved this documentation to the POJO that represents
your JSON object. You just add Javadoc to the fields and it will end
up in the documentation.

Features:

* Jackson visitor that gathers the whole JSON structure and includes Javadoc
and constraint annotations on the fields. It works for both request and
response bodies. In addition to the constraint documentation support that
is already in Spring REST Docs, the constraint message is automatically included
in the documentation. Constraint groups are also supported.
* Path and query parameters can be documented automatically.
* A helper to document authentication.
* A snippet that includes all other snippets and thus helps
you write even less.

[[faq]]
== FAQ

[qanda]
Does it work with Spring Web MVC tests?::
  Yes, take a look at the https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/java-webmvc[example].
Does it work with Spring WebFlux?::
  Yes, take a look at the https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/java-webflux[example].
Is Kotlin supported?::
  Yes, Spring Auto REST Docs 1.0.13 and 2.0.0 introduced Kotlin support.
  Instead of the Javadoc Doclet one has to use the Dokka extension
  `spring-auto-restdocs-dokka-json`. The extension is only available as 2.0.x,
  but works with both version of Spring Auto REST Docs. Take a look at the
  https://github.com/ScaCap/spring-auto-restdocs/tree/master/samples/kotlin-webmvc[example].
Is Java 9/10/11 supported?::
  Yes, see <<gettingstarted,Getting Started>>.
Does it work with REST Assured tests?::
  Not yet. We may add support for REST Assured in the future, but your PR is also welcome.
Is Jackson required for automatic field documentation?::
  Yes, this project only includes a Jackson visitor so far.
Is a multi-module project setup supported?::
  The JSON doclet and the REST Docs snippets produce files.
  Therefore, all files should be placed on the filesystem.
  JSON files will be additionally looked up from classpath,
  so modularization of codebase is fully supported.
  For advanced customization, multiple source directories for the JSON files
  can be configured (see <<gettingstarted-usage,usage>>).
Can Spring REST Docs and Spring Auto REST Docs features be combined?::
  Yes, this even works in the same test.
  One can generate Spring REST Docs snippets and Spring Auto REST Docs snippets out of the same test.
  This is demonstrated in the example project.
Can I regenerate the final HTML without running all tests?::
  Yes, if you do not need the snippets generated out of the test to be updated,
  Asciidoctor can be executed standalone. With Maven you can run
  `mvn asciidoctor:process-asciidoc`
  (where `process-asciidoc` is the goal specified in your Maven POM and might differ).
  With Gradle it can be done via `./gradlew asciidoctor` if `asciidoctor` is the name of the Gradle task
  in your setup. You might have to remove `dependsOn test` depending on your setup to run it standalone.
Is HATEOAS supported?::
  Yes, there is basic support for <<snippets-links,links>> and <<snippets-embedded,embedded>> resources.
What should I do if I get a `NoSuchBeanDefinitionException: No bean named 'webHandler' available` exception?::
  This means that the servlet stack instead if the reactive one is active. Make sure that `@EnableWebFlux` is used.

include::getting-started.adoc[]

include::snippets.adoc[]

include::constraints.adoc[]

include::other.adoc[]

include::integrations.adoc[]

include::contributing.adoc[]
