= Spring Auto REST Docs
Scalable Capital
:doctype: book
:icons: font
:source-highlighter: highlightjs
:highlightjsdir: highlight
:toc: left
:toclevels: 2
:sectlinks:
:table-caption!:
:revnumber: ${project.version}

[[abstract]]

The aim of this extension to Spring REST Docs is to help you to write
even less -- both code and documentation.
You still get the same nice documentation as with Spring REST Docs itself.
The main benefit is that writing less and moving the documentation closer
to the code increases the maintainability of the documentation.

In Spring REST Docs you have to add the documentation for your JSON with
a DSL in your test. We moved this documentation to the POJO that represents
your JSON object. You just add Javadoc to the fields and it will end
up in the documentation.

Features:

* Jackson visitor that gathers the whole JSON structure and includes Javadoc
and constraint annotations on the fields. It works for both request and
response bodies. In addition to the constraint documentation support that
is already in Spring REST Docs, the constraint message is automatically included
in the documentation. Constraint groups are also supported.
* Path and query parameters can be documented automatically.
* A helper to document authentication.
* A snippet that includes all other snippets and thus helps
you write even less.

[[faq]]
== FAQ

[qanda]
Does it work with Spring MVC tests?::
  Yes, it is easy to use in existing or new Spring MVC tests. Take a look at the example.
Does it work with Spring WebTestClient?::
  Yes, but only basic support yet. Take a look at the example.
Does it work with REST Assured tests?::
  Not yet. We may add support for REST Assured in the future, but your PR is also welcome.
Is Jackson required for automatic field documentation?::
  Yes, this project only includes a Jackson visitor so far.
Is a multi-module project setup supported?::
  The JSON doclet and the REST Docs snippets produce files.
  Therefore, all files should be placed on the filesystem.
  JSON files will be additionally looked up from classpath,
  so modularization of codebase is fully supported.
  For advanced customization, multiple source directories for the JSON files
  can be configured (see <<gettingstarted-usage,usage>>).
Can Spring REST Docs and Spring Auto REST Docs features be combined?::
  Yes, this even works in the same test.
  One can generate Spring REST Docs snippets and Spring Auto REST Docs snippets out of the same test.
  This is demonstrated in the example project.
Is Kotlin supported?::
  Yes, Spring Auto REST Docs 1.0.13 and 2.0.0 introduced Kotlin support.
  Instead of the Javadoc Doclet one has to use the Dokka extension
  `spring-auto-restdocs-dokka-json`. The extension is only available as 2.0.x,
  but works with both version of Spring Auto REST Docs.
Is Java 9+ supported?::
  Not yet, because Java 9 introduced a new Doclet API and
  we have not created a Java 9+ Doclet yet.

include::getting-started.adoc[]

include::snippets.adoc[]

include::constraints.adoc[]

include::other.adoc[]

include::contributing.adoc[]
