:master-dir: https://github.com/ScaCap/spring-auto-restdocs/blob/master
:example-dir: {master-dir}/spring-auto-restdocs-example
:core-package: {master-dir}//spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs
:restdocs-package: https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-core/src/main/java/org/springframework/restdocs
:html-preview: https://htmlpreview.github.io/?

[[other]]
== Other

[[paging]]
=== Paging support

Paging support in an endpoint is automatically recognized if request handler method contains `Pageable` parameter
and response is of type `Page`. This is then mentioned in request and response snippets by linking
to common section explaining the details of supported paging parameters/fields.
This section has to be created manually and must be tagged as `\[[overview-pagination]]`.
See example project for link:{example-dir}/src/main/asciidoc/index.adoc#overview-pagination[paging section] template.

[[preprocessors]]
=== Preprocessors

Preprocessors are available for use in order to improve quality of endpoint examples.

- link:{core-package}/response/BinaryReplacementContentModifier.java[binary replacement]: replaces content with `<binary>` for common mime types
- link:{core-package}/response/ArrayLimitingJsonContentModifier.java[limit JSON array length]: limits all JSON arrays to 3 items

For a list of standard preprocessors see link:{restdocs-package}/operation/preprocess/Preprocessors.java[Preprocessors].

[[deprecation]]
=== Deprecation support

Endpoint or field will be marked as deprecated if at least one of these is present:

- method / field is annotated with `@Deprecated`
- method's / field's Javadoc has `@deprecated` tag

Deprecation is shown in the title of an endpoint (also visible in TOC) and description.
Field's deprecation is shown in description column of request/response table. +
See how it looks in the link:{html-preview}{example-dir}/generated-docs/index.html#resources-item-resource-test-clone-item[example project].

[[see-tag]]
=== See tag support

`@see` Javadoc tag comment will be added to the main description section of an endpoint or a field. +
Currently supports only HTML links. Does not support Java code references. +
See how it looks in the link:{html-preview}{example-dir}/generated-docs/index.html#resources-item-resource-test-search[example project].

[[localization]]
=== Localization support

For custom translations of section titles, table headers and other messages:

1. Create a file `SnippetMessages.properties` in `capital.scalable.restdocs.i18n` package.
2. Add translations to the file using keys from link:{master-dir}/spring-auto-restdocs-core/src/test/resources/capital/scalable/restdocs/i18n/DefaultSnippetMessages.properties[DefaultSnippetMessages].[[localization]]

=== Recursive structures support

To prevent infinite loop in recursive structures, annotate the recursive field with `@RestdocsNotExpanded` annotation
from `spring-auto-restdocs-annotations` maven module.
