:master-dir: https://github.com/ScaCap/spring-auto-restdocs/blob/master
:example-dir: {master-dir}/spring-auto-restdocs-example
:core-package: {master-dir}//spring-auto-restdocs-core/src/main/java/capital/scalable/restdocs
:restdocs-package: https://github.com/spring-projects/spring-restdocs/blob/master/spring-restdocs-core/src/main/java/org/springframework/restdocs

[[other]]
== Other

[[paging]]
=== Paging support

Paging support in an endpoint is automatically recognized if request handler method contains `Pageable` parameter
and response is of type `Page`. This is then mentioned in request and response snippets by linking
to common section explaining the details of supported paging parameters/fields.
This section has to be created manally and must be tagged as `\[[overview-pagination]]`.
See example project for link:{example-dir}/src/main/asciidoc/index.adoc#overview-pagination[paging section] template.

[[preprocessors]]
=== Preprocessors

Preprocessors are available for use in order to improve quality of endpoint examples.

- link:{core-package}/response/BinaryReplacementContentModifier.java[binary replacement]: replaces content with `<binary>` for common mime types
- link:{core-package}/response/ArrayLimitingJsonContentModifier.java[limit JSON array length]: limits all JSON arrays to 3 items

For a list of standard preprocessors see link:{restdocs-package}/operation/preprocess/Preprocessors.java[Preprocessors].

[[deprecation]]
=== Deprecation support

Endpoint or field will be marked as deprecated if at least one of these is present:

- method / field is annotated with `@Deprecated`
- method's / field's Javadoc has `@deprecated` tag

The deprecation is only visible when using <<snippets-section,Section>> approach. Then it will be shown in the title (also visible in
TOC) and description. Field's deprecation is shown in description column of request/response table.
See how it looks in the link:https://htmlpreview.github.io/?https://github.com/ScaCap/spring-auto-restdocs/blob/master/spring-auto-restdocs-example/generated-docs/index.html#resources-item-resource-test-clone-item[example project].
