[[snippets]]
== Snippets

[[snippets-authorization]]
=== Authorization snippet

The authorization snippet does not help in adding authorization to your tests, but it makes it easy to document your authorization information.
Usually, a custom `RequestPostProcessor` is used to add authorization and this is also the place where you add the documentation.

.Code
[source,java,indent=0,role="secondary"]
----
protected RequestPostProcessor userToken() {
    return new RequestPostProcessor() {
        @Override
        public MockHttpServletRequest postProcessRequest(MockHttpServletRequest request) {
            // <Code to get access token>
            request.addHeader("Authorization", "Bearer " + accessToken);
            return documentAuthorization(request, "User access token required.");
        }
    };
}
----

[[snippets-path-parameters]]
=== Path parameter snippet

The path parameter snippet automatically lists parameters in the path including their type, whether they are optional, and their JavaDoc.

.Code
[source,java,indent=0,role="secondary"]
----
/**
 * @param id ID of the item.
 */
@RequestMapping("{id}")
public ItemResponse getItem(@PathVariable("id") String id) {
----

. Result
|===
|Parameter|Type|Optional|Description

| id
| String
| false
| ID of the item.
|===

[[snippets-request-parameters]]
=== Request parameter snippet

The request parameter snippet automatically lists query parameters including their type, whether they are optional, and their JavaDoc.

.Code
[source,java,indent=0,role="secondary"]
----
/**
 * @param descMatch Lookup on description field.
 */
@RequestMapping("search")
public Page<ItemResponse> searchItem(@RequestParam("desc") String descMatch) {
----

.Result
|===
|Parameter|Type|Optional|Description

| desc
| String
| false
| Lookup on description field.
|===

include::section-snippet.adoc[]

